apiVersion: apps/v1
kind: Deployment
metadata:
  name: weapp-dep
spec:
  minReadySeconds: 40
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: webapp
      env: dev
  template:
    metadata:
      labels:
        app: webapp
        env: dev
    spec:
      containers:
        - name: webapp
          image: aravindh146/dbconnectiontestapp:latest
          ports:
            - containerPort: 8080
              protocol: "TCP"
          livenessProbe:
            failureThreshold: 2
            initialDelaySeconds: 5
            successThreshold: 1
            httpGet:
              path: "/"
              port: 8080     
        
        
        
        
        
        
        
