apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep
  namesapce: sampleapp
spec:
  minReadySeconds: 40
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: mysql
      env: dev
  template:
    metadata:
      labels:
        app: mysql
        env: dev
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
              protocol: "TCP"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "mydb"
            - name: MYSQL_USER
              value: "ara"
            - name: MYSQL_PASSWORD
              value: "ara"
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: sampleapp
spec:
  type: ClusterIP  # ✅ Changed from LoadBalancer to ClusterIP (internal access only)
  ports:
    - targetPort: 3306
      port: 3306
      protocol: "TCP"
  selector:
    app: mysql
